#@ Can be invoked by a user with namespace privileges (rather than a cluster-admin)
cd deploy/operator && /home/phantomjinx/programming/go/bin/kustomize edit set namespace hawtio-dev && /home/phantomjinx/programming/go/bin/kustomize edit set image quay.io/hawtio/operator=quay.io/phantomjinx/hawtio-operator:1.3.0-7-202511101115
/home/phantomjinx/programming/go/bin/kustomize build --load-restrictor LoadRestrictionsNone deploy/operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hawtio-operator
  namespace: hawtio-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hawtio-operator
  namespace: hawtio-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hawtio-operator
  template:
    metadata:
      labels:
        name: hawtio-operator
    spec:
      containers:
      - command:
        - hawtio-operator
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: hawtio-operator
        image: quay.io/phantomjinx/hawtio-operator:1.3.0-7-202511101115
        imagePullPolicy: Always
        name: hawtio-operator
        ports:
        - containerPort: 8080
          name: metrics
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 100Mi
      serviceAccountName: hawtio-operator
